# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: routine publish

on:
  push:
    tags:
      - "site_v*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - name: run command via ssh
      uses: fifsky/ssh-action@master
      with:
        command: /root/RemoteNetworking/go.mjs
        host: ${{ secrets.HOST }}
        user: root
        key: ${{ secrets.PRIVATE_KEY}}
